// const { airportNamesLookupTable } = require("./airportNamesLookupTable");

    export const airportNamesLookup = {
      AAL: "Aalborg, Denmark",
      AES: "Aalesund, Norway",
      AAR: "Aarhus, Denmark",
      YXX: "Abbotsford, BC, Canada",
      ABZ: "Aberdeen , Scotland",
      ABR: "Aberdeen, SD , USA ",
      ABJ: "Abidjan, Ivory Coast",
      ABI: "Abilene, TX , USA ",
      AUH: "Abu Dhabi, United Arab Emirates",
      ABV: "Abuja, Nigeria",
      ACA: "Acapulco, Mexico",
      ACC: "Accra, Ghana",
      ADA: "Adana, Turkey",
      ADD: "Addis Ababa, Ethiopia",
      ADL: "Adelaide, S.A., Australia",
      ADE: "Aden, Yemen",
      ADF: "Adiyaman, Turkey",
      AGA: "Agadir, Morocco",
      GUM: "Agana, Guam",
      BQN: "Aguadilla, Puerto Rico",
      AGU: "Aguascalientes, Mexico",
      AHE: "Ahe, French Polynesia",
      AMD: "Ahmedabad, India",
      AJA: "Ajaccio, Corsica, France",
      AXT: "Akita, Japan",
      CAK: "Akron, OH , USA ",
      ALS: "Alamosa, CO , USA ",
      ABY: "Albany, GA , USA ",
      ALB: "Albany, NY , USA ",
      ALL: "Albenga, Italy",
      ABQ: "Albuquerque, NM , USA ",
      ABX: "Albury, N.S.W., Australia",
      ALY: "Alexandria, Egypt",
      HBE: "Alexandria, Egypt",
      AEX: "Alexandria, LA , USA ",
      AXD: "Alexandroupolis, Greece",
      AHO: "Alghero, Sardinia, Italy",
      ALG: "Algiers, Algeria",
      ALC: "Alicante, Spain",
      ASP: "Alice Springs, N.T., Australia",
      NSB: "Alice Town, North Bimini Island, Bahamas",
      ABE: "Allentown, PA , USA ",
      AIA: "Alliance, NE , USA ",
      ALA: "Almaty, Kazakhstan",
      LEI: "Almeria, Spain",
      AOR: "Alor Setar, Malaysia",
      APN: "Alpena, MI , USA ",
      ALF: "Alta, Norway",
      ACH: "Altenrhein, Switzerland",
      AOO: "Altoona, PA , USA ",
      AMA: "Amarillo, TX , USA ",
      AMM: "Amman, Jordan",
      AMS: "Amsterdam, Netherlands",
      YAA: "Anahim Lake, BC, Canada",
      ANC: "Anchorage, AK , USA ",
      AOI: "Ancona, Italy",
      ASD: "Andros Town, Bahamas",
      CRK: "Angeles City, Philippines",
      TER: "Angra do Heroismo, Terceira Island, Azores",
      ESB: "Ankara, Turkey",
      AAE: "Annaba, Algeria",
      NCY: "Annecy, France",
      AYT: "Antalya, Turkey",
      TNR: "Antananarivo, Madagascar",
      ANF: "Antofagasta, Chile",
      ANR: "Antwerp, Belgium",
      AOJ: "Aomori, Japan",
      AOT: "Aosta, Italy",
      ATW: "Appleton, WI , USA ",
      ADU: "Ardabil, Iran",
      AQP: "Arequipa, Peru",
      EFL: "Argostoli, Kefalonia Island, Greece",
      ARI: "Arica, Chile",
      ARH: "Arkhangelsk, Russia",
      ARM: "Armidale, N.S.W., Australia",
      ACE: "Arrecife, Lanzarote Island, Canary Islands",
      ARK: "Arusha, Tanzania",
      YEK: "Arviat, NWT, Canada",
      AJR: "Arvidsjaur, Sweden",
      AVL: "Asheville, NC , USA ",
      ASM: "Asmara, Eritrea",
      ASE: "Aspen, CO , USA ",
      TSE: "Astana, Kazakhstan",
      ASU: "Asuncion, Paraguay",
      ASW: "Aswan, Egypt",
      ATH: "Athens, Greece",
      AHN: "Athens, GA , USA ",
      ATL: "Atlanta, GA , USA ",
      ACY: "Atlantic City, NJ , USA ",
      AKL: "Auckland, New Zealand",
      AGS: "Augusta, GA , USA ",
      AUG: "Augusta, ME , USA ",
      AUS: "Austin, TX , USA ",
      RAR: "Avarua, Rarotonga Island, Cook Islands",
      AYQ: "Ayers Rock, N.T., Australia",
      BCD: "Bacolod, Philippines",
      BJZ: "Badajoz, Spain",
      SDA: "Baghdad, Iraq",
      YBG: "Bagotville, PQ , Canada ",
      YBC: "Baie-Comeau, PQ, Canada",
      BFL: "Bakersfield, CA , USA ",
      BAK: "Baku, Azerbaijan",
      GYD: "Baku, Azerbaijan",
      SOB: "Balaton, Hungary",
      TRE: "Balephuil, Scotland",
      BPN: "Balikpapan, Kalimantan, Indonesia",
      BNK: "Ballina, N.S.W., Australia",
      BBA: "Balmaceda, Chile",
      BWI: "Baltimore, MD , USA ",
      BMV: "Ban Me Thuot, Vietnam",
      BWN: "Bandar Seri Begawan, Brunei",
      BLR: "Bangalore, India",
      BPX: "Bangda, China",
      BKK: "Bangkok, Thailand",
      BGR: "Bangor, ME , USA ",
      BGF: "Bangui, Central African Republic",
      BJL: "Banjul, Gambia",
      BHB: "Bar Harbor, ME , USA ",
      BCN: "Barcelona, Spain",
      BDU: "Bardufoss, Norway",
      BRI: "Bari, Italy",
      BZL: "Barisal, Bangladesh",
      BAQ: "Barranquilla, Colombia",
      BRW: "Barrow, AK, USA ",
      BSL: "Basel, Switzerland",
      SKB: "Basseterre, St. Kitts",
      BIA: "Bastia, Corsica, France",
      BHS: "Bathurst, N.S.W., Australia",
      BTR: "Baton Rouge, LA , USA ",
      BAU: "Bauru, Brazil",
      BPT: "Beaumont, TX , USA ",
      BVA: "Beauvais, France",
      BKW: "Beckley, WV , USA ",
      BED: "Bedford, MA , USA ",
      EIS: "Beef Island, Tortola, British Virgin Islands",
      BJS: "Beijing, China",
      BEY: "Beirut, Lebanon",
      BEL: "Belem, Brazil",
      BFS: "Belfast, Northern Ireland",
      BHD: "Belfast, Northern Ireland",
      BEG: "Belgrade, Serbia and Montenegro",
      BZE: "Belize City, Belize",
      BLI: "Bellingham, WA , USA ",
      CNF: "Belo Horizonte, Brazil",
      BJI: "Bemidji, MN , USA ",
      BEB: "Benbecula, Scotland",
      BUG: "Benguela, Angola",
      BGO: "Bergen, Norway",
      BER: "Berlin, Germany",
      SXF: "Berlin, Germany",
      THF: "Berlin, Germany",
      TXL: "Berlin, Germany",
      BRN: "Berne, Switzerland",
      BET: "Bethel, AK , USA ",
      BTT: "Bettles, AK , USA ",
      BIK: "Biak, Papua, Indonesia",
      BIQ: "Biarritz, France",
      BIO: "Bilbao, Spain",
      BIL: "Billings, MT , USA ",
      BLL: "Billund, Denmark",
      BGM: "Binghamton, NY , USA ",
      BTU: "Bintulu, Sarawak, Malaysia",
      BHX: "Birmingham, England",
      BHM: "Birmingham, AL , USA ",
      FRU: "Bishkek, Kyrgyzstan",
      BIS: "Bismarck, ND , USA ",
      OXB: "Bissau, Guinea-Bissau",
      BLZ: "Blantyre, Malawi",
      BHE: "Blenheim, New Zealand",
      BFN: "Bloemfontein, South Africa",
      BMI: "Bloomington, IL , USA ",
      BMG: "Bloomington, IN , USA ",
      BLF: "Bluefield, WV , USA ",
      BOO: "Bodo, Norway",
      BOG: "Bogota, Colombia",
      BOI: "Boise, ID , USA ",
      BLQ: "Bologna, Italy",
      BZO: "Bolzano, Italy",
      BOD: "Bordeaux, France",
      BLE: "Borlange, Sweden",
      BOS: "Boston, MA , USA ",
      BZN: "Bozeman, MT , USA ",
      BSB: "Brasilia, Brazil",
      BTS: "Bratislava, Slovakia",
      BZV: "Brazzaville, Congo",
      BRE: "Bremen, Germany",
      BES: "Brest, France",
      BGI: "Bridgetown, Barbados",
      BDS: "Brindisi, Italy",
      BNE: "Brisbane, Qld., Australia",
      BRS: "Bristol, England",
      BHQ: "Broken Hill, N.S.W., Australia",
      BKX: "Brookings, SD , USA ",
      BME: "Broome, W.A., Australia",
      BRO: "Brownsville, TX , USA ",
      BQK: "Brunswick, GA , USA ",
      BRU: "Brussels, Belgium",
      OTP: "Bucharest, Romania",
      BUD: "Budapest, Hungary",
      EZE: "Buenos Aires, Argentina",
      BUF: "Buffalo, NY , USA ",
      BJM: "Bujumbura, Burundi",
      BUQ: "Bulawayo, Zimbabwe",
      BDB: "Bundaberg, Qld., Australia",
      BUR: "Burbank, CA , USA ",
      BFV: "Buri Ram, Thailand",
      BRL: "Burlington, IA , USA ",
      BBF: "Burlington, MA , USA ",
      BTV: "Burlington, VT , USA ",
      PUS: "Busan, Korea, Republic of",
      BTM: "Butte, MT , USA ",
      BXU: "Butuan, Philippines",
      BZG: "Bydgoszcz, Poland",
      CFR: "Caen, France",
      CGY: "Cagayan de Oro, Philippines",
      CAG: "Cagliari, Sardinia, Italy",
      CNS: "Cairns, Qld., Australia",
      CAI: "Cairo, Egypt",
      CCU: "Calcutta, India",
      YYC: "Calgary, AB , Canada ",
      CLO: "Cali, Colombia",
      CLY: "Calvi, Corsica, France",
      YBL: "Campbell River, BC , Canada ",
      CAL: "Campbeltown, Scotland",
      CPE: "Campeche, Mexico",
      CBR: "Canberra, A.C.T., Australia",
      CUN: "Cancun, Mexico",
      YGR: "Cap-aux-Meules, Magdalens Islands, PQ, Canada",
      CGI: "Cape Girardeau, MO , USA ",
      CPT: "Cape Town, South Africa",
      CCS: "Caracas, Venezuela",
      CWL: "Cardiff, Wales",
      CLD: "Carlsbad, CA , USA ",
      CNM: "Carlsbad, NM , USA ",
      CTG: "Cartagena, Colombia",
      CMN: "Casablanca, Morocco",
      CPR: "Casper, WY , USA ",
      YCG: "Castlegar, BC, Canada",
      SLU: "Castries, St. Lucia",
      CTA: "Catania, Sicily, Italy",
      CAY: "Cayenne, French Guiana",
      CYB: "Cayman Brac, Cayman Islands",
      CEB: "Cebu, Philippines",
      CID: "Cedar Rapids, IA , USA ",
      CED: "Ceduna, S.A., Australia",
      CMI: "Champaign, IL , USA ",
      CGQ: "Changchun, China",
      CSX: "Changsha, China",
      CHQ: "Chania, Crete, Greece",
      CHS: "Charleston, SC , USA ",
      CRW: "Charleston, WV , USA ",
      CTL: "Charleville, Qld., Australia",
      STT: "Charlotte Amalie, St. Thomas, U.S. Virgin Islands",
      CLT: "Charlotte, NC , USA ",
      CHO: "Charlottesville, VA , USA ",
      YYG: "Charlottetown, PEI , Canada ",
      CHA: "Chattanooga, TN , USA ",
      CTU: "Chengdu, China",
      MAA: "Chennai (Madras), India",
      CTM: "Chetumal, Mexico",
      CYS: "Cheyenne, WY , USA ",
      CNX: "Chiang Mai, Thailand",
      CEI: "Chiang Rai, Thailand",
      YMT: "Chibougamau, PQ , Canada ",
      CHI: "Chicago, IL , USA ",
      MDW: "Chicago, IL , USA ",
      ORD: "Chicago, IL , USA ",
      CIC: "Chico, CA , USA ",
      CUU: "Chihuahua, Mexico",
      JKH: "Chios, Greece",
      KIV: "Chisinau, Moldova",
      CKG: "Chongqing, China",
      CHC: "Christchurch, New Zealand",
      STX: "Christiansted, St. Croix, U.S. Virgin Islands",
      YYQ: "Churchill, MB , Canada ",
      CVG: "Cincinnati, OH , USA ",
      CBL: "Ciudad Bolivar, Venezuela",
      CME: "Ciudad Del Carmen, Mexico",
      AGT: "Ciudad del Este, Paraguay",
      CJS: "Ciudad Juarez, Mexico",
      CEN: "Ciudad Obregon, Mexico",
      CVM: "Ciudad Victoria, Mexico",
      CKB: "Clarksburg, WV , USA ",
      CFE: "Clermont-Ferrand, France",
      CLE: "Cleveland, OH , USA ",
      CVN: "Clovis, NM , USA ",
      ZSA: "Cockburn Town, San Salvador Island, Bahamas",
      COD: "Cody, WY , USA ",
      CFS: "Coffs Harbour, N.S.W., Australia",
      CLQ: "Colima, Mexico",
      CLL: "College Station, TX , USA ",
      CGN: "Cologne, Germany",
      CMB: "Colombo, Sri Lanka",
      COS: "Colorado Springs, CO , USA ",
      COU: "Columbia, MO , USA ",
      CAE: "Columbia, SC , USA ",
      CSG: "Columbus, GA , USA ",
      CLU: "Columbus, IN , USA ",
      GTR: "Columbus, MS , USA ",
      OLU: "Columbus, NE , USA ",
      CMH: "Columbus, OH , USA ",
      CKY: "Conakry, Guinea",
      CCP: "Concepcion, Chile",
      NOC: "Connaught, Ireland",
      CPD: "Coober Pedy, S.A., Australia",
      CPH: "Copenhagen, Denmark",
      CPO: "Copiapo, Chile",
      COR: "Cordoba, Argentina",
      CDV: "Cordova, AK , USA ",
      ORK: "Cork, Ireland",
      CRP: "Corpus Christi, TX , USA ",
      CBO: "Cotabato, Philippines",
      CZM: "Cozumel, Mexico",
      YXC: "Cranbrook, BC , Canada ",
      CRV: "Crotone, Italy",
      NCP: "Cubi Point Nas, Philippines",
      CUL: "Culiacan, Mexico",
      CWB: "Curitiba, Brazil",
      CUZ: "Cusco, Peru",
      DAD: "Da Nang, Vietnam",
      DKR: "Dakar, Senegal",
      DLM: "Dalaman, Turkey",
      DLU: "Dali City, China",
      DLC: "Dalian, China",
      DAL: "Dallas, TX , USA ",
      DFW: "Dallas, TX , USA ",
      DAM: "Damascus, Syria",
      DGA: "Dangriga, Belize",
      DAR: "Dar es Salaam, Tanzania",
      DRW: "Darwin, N.T., Australia",
      DVO: "Davao, Philippines",
      DWD: "Dawadmi, Saudi Arabia",
      DYG: "Dayong, China",
      DAY: "Dayton, OH , USA ",
      DAB: "Daytona Beach, FL , USA ",
      LGI: "Deadmans Cay, Long Island, Bahamas",
      DOY: "Deboyne, Papua-New Guinea",
      DEC: "Decatur, IL , USA ",
      YDF: "Deer Lake, NF , Canada ",
      DEL: "Delhi, India",
      DPS: "Denpasar, Bali, Indonesia",
      DEN: "Denver, CO , USA ",
      DSM: "Des Moines, IA , USA ",
      DTT: "Detroit, MI , USA ",
      DTW: "Detroit, MI , USA ",
      DVL: "Devils Lake, ND , USA ",
      DPO: "Devonport, Tas., Australia",
      DHA: "Dhahran, Saudi Arabia",
      DAC: "Dhaka, Bangladesh",
      DIK: "Dickinson, ND , USA ",
      DIN: "Dien-Bien-Phu, Vietnam",
      DLG: "Dillingham, AK , USA ",
      DPL: "Dipolog, Philippines",
      JIB: "Djibouti, Djibouti",
      DNK: "Dnepropetrovsk, Ukraine",
      DDC: "Dodge City, KS , USA ",
      DOH: "Doha, Qatar",
      DSA: "Doncaster, England",
      DOK: "Donetsk, Ukraine",
      DTM: "Dortmund, Germany",
      DHN: "Dothan, AL , USA ",
      DLA: "Douala, Cameroon",
      DRS: "Dresden, Germany",
      YHD: "Dryden, ON , Canada ",
      DUJ: "Du Bois, PA , USA ",
      DXB: "Dubai, United Arab Emirates",
      DBO: "Dubbo, N.S.W., Australia",
      DUB: "Dublin, Ireland",
      DBV: "Dubrovnik, Croatia",
      DBQ: "Dubuque, IA , USA ",
      DLH: "Duluth, MN , USA ",
      DGT: "Dumaguete, Philippines",
      DUD: "Dunedin, New Zealand",
      DGO: "Durango, Mexico",
      DRO: "Durango, CO , USA ",
      DUR: "Durban, South Africa",
      DYU: "Dushanbe, Tajikistan",
      DUS: "Dusseldorf, Germany",
      DUT: "Dutch Harbor, Un Island, AK, USA ",
      ELS: "East London, South Africa",
      EMA: "East Midlands, England",
      EAU: "Eau Claire, WI , USA ",
      EDI: "Edinburgh, Scotland",
      YEG: "Edmonton, AB , Canada ",
      EEK: "Eek, AK , USA ",
      SVX: "Ekaterinburg, Siberia, Russia",
      FTE: "El Calafate, Argentina",
      IPL: "El Centro, CA , USA ",
      ELD: "El Dorado, AR , USA ",
      ELP: "El Paso, TX , USA ",
      ESR: "El Salvador, Chile",
      EKO: "Elko, NV , USA ",
      ELM: "Elmira, NY , USA ",
      EMD: "Emerald, Qld., Australia",
      WDG: "Enid, OK , USA ",
      EBB: "Entebbe, Uganda",
      ERF: "Erfurt, Germany",
      ERI: "Erie, PA , USA ",
      EBJ: "Esbjerg, Denmark",
      ESC: "Escanaba, MI , USA ",
      EUG: "Eugene, OR , USA ",
      ACV: "Eureka, CA, USA ",
      EVV: "Evansville, IN , USA ",
      EVE: "Evenes, Norway",
      FAI: "Fairbanks, AK , USA ",
      FAR: "Fargo, ND , USA ",
      FMN: "Farmington, NM , USA ",
      FAO: "Faro, Portugal",
      XNA: "Fayetteville, AR , USA ",
      FAY: "Fayetteville, NC , USA ",
      FEN: "Fernando de Noronha, Brazil",
      FSC: "Figari, Corsica, France",
      FLG: "Flagstaff, AZ , USA ",
      YFO: "Flin Flon, MB, Canada",
      FNT: "Flint, MI , USA ",
      FLR: "Florence, Italy",
      FLO: "Florence, SC , USA ",
      FRS: "Flores, Guatemala",
      FOD: "Fort Dodge, IA , USA ",
      FLL: "Fort Lauderdale, FL , USA ",
      TBN: "Fort Leonard Wood, MO, USA ",
      YMM: "Fort McMurray, AB , Canada ",
      RSW: "Fort Myers, FL , USA ",
      YYE: "Fort Nelson, BC , Canada ",
      YXJ: "Fort Saint John, BC , Canada ",
      FSM: "Fort Smith, AR , USA ",
      YSM: "Fort Smith, NWT, Canada ",
      VPS: "Fort Walton Beach, FL , USA ",
      FWA: "Fort Wayne, IN , USA ",
      FYU: "Fort Yukon, AK , USA ",
      FDF: "Fort-de-France, Martinique",
      FRA: "Frankfurt, Germany",
      YFC: "Fredericton, NB , Canada ",
      FPO: "Freeport, Grand Bahama Island, Bahamas",
      FNA: "Freetown, Sierra Leone",
      FAT: "Fresno, CA , USA ",
      FDH: "Friedrichshafen, Germany",
      FUK: "Fukuoka, Japan",
      FKS: "Fukushima, Japan",
      FNC: "Funchal, Madeira",
      FOC: "Fuzhou, China",
      GNV: "Gainesville, FL , USA ",
      YQX: "Gander, NF , Canada ",
      GCK: "Garden City, KS, USA ",
      YGP: "Gaspe, PQ , Canada ",
      GDN: "Gdansk, Poland",
      GES: "General Santos, Philippines",
      GVA: "Geneva, Switzerland",
      GOA: "Genoa, Italy",
      GGT: "George Town, Great Exuma Island, Bahamas",
      GEO: "Georgetown, Guyana",
      GCM: "Georgetown, Grand Cayman Island, Cayman Islands",
      GCC: "Gillette, WY , USA ",
      GIS: "Gisborne, New Zealand",
      GLT: "Gladstone, Qld., Australia",
      GLA: "Glasgow, Scotland",
      PIK: "Glasgow, Scotland",
      GDV: "Glendive, MT , USA ",
      OOL: "Gold Coast, Qld., Australia",
      GOT: "Gothenburg, Sweden",
      GOV: "Gove, N.T., Australia",
      GHB: "Governor's Harbour, Eleuthera Island, Bahamas",
      GRX: "Granada, Spain",
      GFK: "Grand Forks, ND , USA ",
      GRI: "Grand Island, NE , USA ",
      GJT: "Grand Junction, CO , USA ",
      GRR: "Grand Rapids, MI , USA ",
      YQU: "Grande Prairie, AB , Canada ",
      GRZ: "Graz, Austria",
      GBD: "Great Bend, KS , USA ",
      GTF: "Great Falls, MT , USA ",
      GRB: "Green Bay, WI , USA ",
      LWB: "Greenbrier, WV, USA ",
      GSO: "Greensboro, NC , USA ",
      GLH: "Greenville, MS , USA ",
      PGV: "Greenville, NC , USA ",
      GSP: "Greenville, SC , USA ",
      GFF: "Griffith, N.S.W., Australia",
      GDL: "Guadalajara, Mexico",
      CAN: "Guangzhou, China",
      GUA: "Guatemala City, Guatemala",
      GYE: "Guayaquil, Ecuador",
      GYM: "Guaymas, Mexico",
      GCI: "Guernsey, Channel Islands",
      KWL: "Guilin, China",
      GPT: "Gulfport, MS , USA ",
      GUC: "Gunnison, CO , USA ",
      SBH: "Gustavia, St. Barts",
      HGR: "Hagerstown, MD , USA ",
      HAK: "Haikou, Hainan Island, China",
      HLD: "Hailar, China",
      HKD: "Hakodate, Japan",
      YHZ: "Halifax, NS , Canada ",
      HAD: "Halmstad, Sweden",
      HAM: "Hamburg, Germany",
      BDA: "Hamilton, Bermuda",
      HLZ: "Hamilton, New Zealand",
      HTI: "Hamilton Island, Whitsunday Island, Qld., Australia",
      YHM: "Hamilton, ON , Canada ",
      HFT: "Hammerfest, Norway",
      HNM: "Hana, Maui, HI, USA ",
      CMX: "Hancock, MI , USA ",
      IPC: "Hanga Roa, Easter Island, Chile",
      HGH: "Hangzhou, China",
      HAJ: "Hannover, Germany",
      HAN: "Hanoi, Vietnam",
      HRE: "Harare, Zimbabwe",
      HRB: "Harbin, China",
      HRL: "Harlingen, TX , USA ",
      MDT: "Harrisburg, PA , USA ",
      HRO: "Harrison, AR , USA ",
      BDL: "Hartford, CT , USA ",
      HDY: "Hat Yai, Thailand",
      HAU: "Haugesund, Norway",
      HAV: "Havana, Cuba",
      HVR: "Havre, MT , USA ",
      HYS: "Hays, KS, USA ",
      HFE: "Hefei, China",
      HLN: "Helena, MT , USA ",
      AGH: "Helsingborg, Sweden",
      HEL: "Helsinki, Finland",
      HMV: "Hemavan, Sweden",
      HCN: "Hengchun, Taiwan",
      HER: "Heraklion, Crete, Greece",
      HMO: "Hermosillo, Mexico",
      HIB: "Hibbing, MN , USA ",
      Big: "Hilo, Hawaii , USA ",
      HHH: "Hilton Head Island, SC , USA ",
      SGN: "Ho Chi Minh City (Saigon), Vietnam",
      HBA: "Hobart, Tas., Australia",
      HOB: "Hobbs, NM , USA ",
      HOQ: "Hof, Germany",
      HET: "Hohhot, China",
      HKK: "Hokitika, New Zealand",
      HOM: "Homer, AK, USA ",
      HKG: "Hong Kong, China",
      HIR: "Honiara, Guadalcanal, Solomon Islands",
      HNL: "Honolulu, Oahu, HI, USA ",
      MKK: "Hoolehua, Molokai, HI, USA ",
      HID: "Horn Island, Qld., Australia",
      HOT: "Hot Springs, AR , USA ",
      DJE: "Houmt Souk, Tunisia",
      EFD: "Houston, TX , USA ",
      HOU: "Houston, TX , USA ",
      IAH: "Houston, TX , USA ",
      HUN: "Hualien, Taiwan",
      HUI: "Hue, Vietnam",
      HUY: "Humberside, England",
      HTS: "Huntington, WV , USA ",
      HSV: "Huntsville, AL , USA ",
      HRG: "Hurghada, Egypt",
      HON: "Huron, SD, USA ",
      HYA: "Hyannis, MA , USA ",
      HYD: "Hyderabad, India",
      IBA: "Ibadan, Nigeria",
      IBZ: "Ibiza, Spain",
      IDA: "Idaho Falls, ID , USA ",
      JIK: "Ikaria Island, Greece",
      ILO: "Iloilo, Philippines",
      IND: "Indianapolis, IN , USA ",
      INN: "Innsbruck, Austria",
      INL: "International Falls, MN , USA ",
      IVC: "Invercargill, New Zealand",
      INV: "Inverness, Scotland",
      IYK: "Inyokern, CA , USA ",
      IOA: "Ioannina, Greece",
      IPH: "Ipoh, Malaysia",
      YFB: "Iqaluit, Nunavut , Canada ",
      IKT: "Irkutsk, Siberia, Russia",
      IMT: "Iron Mountain, MI , USA ",
      IWD: "Ironwood, MI, USA ",
      ISB: "Islamabad-Rawalpindi, Pakistan",
      ILY: "Islay Island, Scotland",
      ISP: "Islip, NY , USA ",
      IST: "Istanbul, Turkey",
      SAW: "Istanbul, Turkey",
      ITH: "Ithaca, NY , USA ",
      IVL: "Ivalo, Finland",
      IWJ: "Iwami, Japan",
      ZIH: "Ixtapa, Mexico",
      ADB: "Izmir, Turkey",
      IZO: "Izumo, Japan",
      JAC: "Jackson Hole, WY , USA ",
      JAN: "Jackson, MS , USA ",
      MKL: "Jackson, TN , USA ",
      JAX: "Jacksonville, FL , USA ",
      OAJ: "Jacksonville, NC , USA ",
      CGK: "Jakarta, Java, Indonesia",
      JKT: "Jakarta, Java, Indonesia",
      JAL: "Jalapa, Mexico",
      JMS: "Jamestown, ND , USA ",
      JHW: "Jamestown, NY , USA ",
      JED: "Jeddah, Saudi Arabia",
      CJU: "Jeju, Korea, Republic of",
      XRY: "Jerez de La Frontera, Spain",
      JER: "Jersey, Channel Islands",
      JMU: "Jiamusi, China",
      JIJ: "Jijiga, Ethiopia",
      JOE: "Joensuu, Finland",
      JNB: "Johannesburg, South Africa",
      JST: "Johnstown, PA , USA ",
      JHB: "Johor Bahru, Malaysia",
      JBR: "Jonesboro, AR , USA ",
      JKG: "Jonkoping, Sweden",
      JLN: "Joplin, MO , USA ",
      JNU: "Juneau, AK , USA ",
      JYV: "Jyvaskyla, Finland",
      KBL: "Kabul, Afghanistan",
      KOJ: "Kagoshima, Japan",
      OGG: "Kahului, Maui, HI , USA ",
      KAT: "Kaitaia, New Zealand",
      KAJ: "Kajaani, Finland",
      AZO: "Kalamazoo, MI , USA ",
      LUP: "Kalaupapa, Molokai, HI, USA ",
      KGI: "Kalgoorlie, W.A., Australia",
      KLO: "Kalibo, Philippines",
      KGD: "Kaliningrad, Russia",
      FCA: "Kalispell, MT , USA ",
      KLR: "Kalmar, Sweden",
      YKA: "Kamloops, BC , Canada ",
      KOA: "Kamuela, Hawaii , USA ",
      MCI: "Kansas City, MO , USA ",
      KHH: "Kaohsiung, Taiwan",
      JHM: "Kapalua, Maui, HI, USA ",
      KHI: "Karachi, Pakistan",
      KGF: "Karaganda, Kazakhstan",
      KSD: "Karlstad, Sweden",
      KTA: "Karratha, W.A., Australia",
      KRP: "Karup, Denmark",
      KHG: "Kashi, China",
      KTM: "Kathmandu, Nepal",
      KTW: "Katowice, Poland",
      EAR: "Kearney, NE , USA ",
      YLW: "Kelowna, BC , Canada ",
      ENA: "Kenai, AK , USA ",
      YQK: "Kenora, ON, Canada",
      KKE: "Kerikeri, New Zealand",
      KTN: "Ketchikan, AK , USA ",
      EYW: "Key West, FL , USA ",
      HRK: "Kharkov, Ukraine",
      KRT: "Khartoum, Sudan",
      KKC: "Khon Kaen, Thailand",
      KEL: "Kiel, Germany",
      KBP: "Kiev, Ukraine",
      KGL: "Kigali, Rwanda",
      GRK: "Killeen, TX , USA ",
      AKN: "King Salmon, AK, USA ",
      IGM: "Kingman, AZ , USA ",
      KGC: "Kingscote, Kangaroo Island, S.A., Australia",
      KIN: "Kingston, Jamaica",
      KTP: "Kingston, Jamaica",
      YGK: "Kingston, ON , Canada ",
      SVD: "Kingstown, St. Vincent",
      FIH: "Kinshasa, Zaire",
      IRK: "Kirksville, MO , USA ",
      KOI: "Kirkwall, Orkney Islands, Scotland",
      KRN: "Kiruna, Sweden",
      FKI: "Kisangani, Zaire",
      KTT: "Kittila, Finland",
      KLU: "Klagenfurt, Austria",
      LMT: "Klamath Falls, OR , USA ",
      TYS: "Knoxville, TN , USA ",
      ADQ: "Kodiak, AK , USA ",
      USM: "Koh Samui, Thailand",
      KOK: "Kokkola, Finland",
      KMQ: "Komatsu, Japan",
      ROR: "Koror, Palau",
      KGS: "Kos, Greece",
      KSA: "Kosrae, Micronesia",
      KBR: "Kota Bharu, Malaysia",
      BKI: "Kota Kinabalu, Sabah, Malaysia",
      KBV: "Krabi, Thailand",
      KRK: "Krakow, Poland",
      BON: "Kralendijk, Bonaire",
      KRF: "Kramfors, Sweden",
      KRS: "Kristiansand, Norway",
      KID: "Kristianstad, Sweden",
      KUL: "Kuala Lumpur, Malaysia",
      TGG: "Kuala Terengganu, Malaysia",
      KUA: "Kuantan, Malaysia",
      KCH: "Kuching, Sarawak, Malaysia",
      KMJ: "Kumamoto, Japan",
      KMG: "Kunming, China",
      KUO: "Kuopio, Finland",
      KUH: "Kushiro, Japan",
      KWI: "Kuwait, Kuwait",
      KZO: "Kzyl Orda, Kazakhstan",
      LCG: "La Coruna, Spain",
      LSE: "La Crosse, WI , USA ",
      LAP: "La Paz, Mexico",
      LPB: "La Paz, Bolivia",
      LRM: "La Romana, Dominican Republic",
      LSC: "La Serena, Chile",
      LFT: "Lafayette, LA , USA ",
      LOS: "Lagos, Nigeria",
      LDU: "Lahad Datu, Sabah, Malaysia",
      LHE: "Lahore, Pakistan",
      LCH: "Lake Charles, LA , USA ",
      HII: "Lake Havasu City, AZ , USA ",
      SUF: "Lamezia Terme, Italy",
      LNY: "Lanai City, Lanai, HI, USA ",
      LNS: "Lancaster, PA , USA ",
      LGK: "Langkawi, Malaysia",
      LAI: "Lannion, France",
      LAN: "Lansing, MI , USA ",
      LHW: "Lanzhou, China",
      LAR: "Laramie, WY , USA ",
      LRD: "Laredo, TX , USA ",
      LCA: "Larnaca, Cyprus",
      LRU: "Las Cruces, NM , USA ",
      LPA: "Las Palmas, Grand Canary Island, Canary Islands",
      LAS: "Las Vegas, NV , USA ",
      LBE: "Latrobe, PA , USA ",
      LST: "Launceston, Tas., Australia",
      PIB: "Laurel, MS , USA ",
      LAW: "Lawton, OK , USA ",
      LZC: "Lazaro Cardenas, Mexico",
      LEH: "Le Havre, France",
      LEB: "Lebanon, NH , USA ",
      LBA: "Leeds, England",
      LGP: "Legaspi, Philippines",
      LEJ: "Leipzig, Germany",
      BJX: "Leon, Mexico",
      LEN: "Leon, Spain",
      LSI: "Lerwick, Shetland Islands, Scotland",
      YQL: "Lethbridge, AB , Canada ",
      LWS: "Lewiston, ID , USA ",
      LEW: "Lewiston, ME , USA ",
      LWT: "Lewistown, MT , USA ",
      LEX: "Lexington, KY , USA ",
      LXA: "Lhasa, Tibet, China",
      LBL: "Liberal, KS, USA ",
      LIR: "Liberia, Costa Rica",
      LBV: "Libreville, Gabon",
      LIH: "Lihue, Kauai, HI, USA ",
      LJG: "Lijiang City, China",
      LIL: "Lille, France",
      LLW: "Lilongwe, Malawi",
      LIM: "Lima, Peru",
      LIG: "Limoges, France",
      LNJ: "Lincang, China",
      LNK: "Lincoln, NE , USA ",
      LPI: "Linkoping, Sweden",
      LNZ: "Linz, Austria",
      LIS: "Lisbon, Portugal",
      LIT: "Little Rock, AR , USA ",
      LPL: "Liverpool, England",
      LJU: "Ljubljana, Slovenia",
      RJL: "Logrono, Spain",
      LFW: "Lome, Togo",
      LCY: "London, England",
      LGW: "London, England",
      LHR: "London, England",
      LON: "London, England",
      STN: "London, England",
      YXU: "London, ON , Canada ",
      LDY: "Londonderry, Northern Ireland",
      LBP: "Long Banga, Malaysia",
      LGB: "Long Beach, CA , USA ",
      LRE: "Longreach, Qld., Australia",
      GGG: "Longview, TX , USA ",
      LYR: "Longyearbyen, Svalbard, Norway",
      LTO: "Loreto, Mexico",
      LRT: "Lorient, France",
      LAX: "Los Angeles, CA , USA ",
      QLA: "Los Angeles, CA , USA ",
      SJD: "Los Cabos, Mexico",
      SDF: "Louisville, KY, USA , USA ",
      LDE: "Lourdes, France",
      LAD: "Luanda, Angola",
      LBB: "Lubbock, TX , USA ",
      FBM: "Lubumbashi, Zaire",
      LUG: "Lugano, Switzerland",
      VSG: "Lugansk, Ukraine",
      LUA: "Lukla, Nepal",
      LLA: "Lulea, Sweden",
      LUN: "Lusaka, Zambia",
      LTN: "Luton, England",
      LUX: "Luxembourg, Luxembourg",
      LXR: "Luxor, Egypt",
      LYC: "Lycksele, Sweden",
      LYH: "Lynchburg, VA , USA ",
      LYS: "Lyon, France",
      MKY: "Mackay, Qld., Australia",
      MCN: "Macon, GA , USA ",
      MSN: "Madison, WI , USA ",
      MAD: "Madrid, Spain",
      HGN: "Mae Hong Son, Thailand",
      MRU: "Mahebourg, Mauritius",
      MAJ: "Majuro, Marshall Islands",
      AAM: "Mala Mala, South Africa",
      SSG: "Malabo, Bioko Island, Equatorial Guinea",
      AGP: "Malaga, Spain",
      MLE: "Male, Maldives",
      MMA: "Malmo, Sweden",
      MMX: "Malmo, Sweden",
      MGA: "Managua, Nicaragua",
      BAH: "Manama, Bahrain",
      MAO: "Manaus, Brazil",
      MAN: "Manchester, England",
      MHT: "Manchester, NH , USA ",
      MAY: "Mangrove Cay, Andros Island, Bahamas",
      MHK: "Manhattan, KS , USA ",
      MNL: "Manila, Philippines",
      MBL: "Manistee, MI , USA ",
      ZLO: "Manzanillo, Mexico",
      MTS: "Manzini, Swaziland",
      MAH: "Mao, Minorca, Spain",
      MPM: "Maputo, Mozambique",
      MAR: "Maracaibo, Venezuela",
      MHQ: "Mariehamn, Aland, Finland",
      MII: "Marilia, Brazil",
      MWA: "Marion, IL , USA ",
      MPW: "Mariupol, Ukraine",
      MCY: "Maroochydore, Qld., Australia",
      MQT: "Marquette, MI , USA ",
      RAK: "Marrakech, Morocco",
      MRS: "Marseille, France",
      MHH: "Marsh Harbour, Abaco Island, Bahamas",
      MVY: "Martha's Vineyard, MA , USA ",
      MSU: "Maseru, Lesotho",
      MCW: "Mason City, IA , USA ",
      MSS: "Massena, NY , USA ",
      MFK: "Matsu, Taiwan",
      MYJ: "Matsuyama, Japan",
      MZT: "Mazatlan, Mexico",
      MFE: "McAllen, TX , USA ",
      MCK: "McCook, NE , USA ",
      MES: "Medan, Sumatra, Indonesia",
      MDE: "Medellin, Colombia",
      MFR: "Medford, OR , USA ",
      YXH: "Medicine Hat, AB , Canada ",
      MLB: "Melbourne, FL , USA ",
      AVV: "Melbourne, Vic., Australia",
      MEL: "Melbourne, Vic., Australia",
      MLN: "Melilla, Spain",
      MMB: "Memanbetsu, Japan",
      MEM: "Memphis, TN , USA ",
      MDZ: "Mendoza, Argentina",
      MID: "Merida, Mexico",
      MEI: "Meridian, MS , USA ",
      MIM: "Merimbula, N.S.W., Australia",
      ETZ: "Metz, France",
      MXL: "Mexicali, Mexico",
      MEX: "Mexico City, Mexico",
      MIA: "Miami, FL , USA ",
      MIG: "Mian Yang, China",
      MAF: "Midland, TX , USA ",
      JMK: "Mikonos, Greece",
      LIN: "Milan, Italy",
      MIL: "Milan, Italy",
      MXP: "Milan, Italy",
      MQL: "Mildura, Vic., Australia",
      MLS: "Miles City, MT, USA ",
      MKE: "Milwaukee, WI , USA ",
      MSP: "Minneapolis, MN , USA ",
      MOT: "Minot, ND , USA ",
      MHP: "Minsk, Belarus",
      MSQ: "Minsk, Belarus",
      MYY: "Miri, Sarawak, Malaysia",
      MSJ: "Misawa, Japan",
      MSO: "Missoula, MT , USA ",
      ORF: "Norfolk, VA , USA ",
      NRK: "Norrkoping, Sweden",
      YYB: "North Bay, ON , Canada ",
      OTH: "North Bend, OR , USA ",
      ELH: "North Eleuthera, Bahamas",
      LBF: "North Platte, NE , USA ",
      NWI: "Norwich, England",
      NKC: "Nouakchott, Mauritania",
      GEA: "Noumea, New Caledonia",
      NOU: "Noumea, New Caledonia",
      OVB: "Novosibirsk, Siberia, Russia",
      NLD: "Nuevo Laredo, Mexico",
      NUE: "Nuremberg, Germany",
      OAK: "Oakland, CA , USA ",
      OAX: "Oaxaca, Mexico",
      OBO: "Obihiro, Japan",
      OCJ: "Ocho Rios, Jamaica",
      ONJ: "Odate Noshiro, Japan",
      ODS: "Odessa, Ukraine",
      OGS: "Ogdensburg, NY , USA ",
      OIT: "Oita, Japan",
      OKC: "Oklahoma City, OK , USA ",
      OLB: "Olbia, Sardinia, Italy",
      OLP: "Olympic Dam, S.A., Australia",
      OMA: "Omaha, NE , USA ",
      OMS: "Omsk, Siberia, Russia",
      ONT: "Ontario, CA , USA ",
      SNA: "Orange County, CA , USA ",
      OAG: "Orange, N.S.W., Australia",
      AUA: "Oranjestad, Aruba",
      EUX: "Oranjestad, St. Eustatius",
      ORB: "Orebro, Sweden",
      MCO: "Orlando, FL , USA ",
      OER: "Ornskoldsvik, Sweden",
      ITM: "Osaka, Japan",
      KIX: "Osaka, Japan",
      OSA: "Osaka, Japan",
      OSH: "Oshkosh, WI , USA ",
      OSL: "Oslo, Norway",
      ZOS: "Osorno, Chile",
      OSD: "Ostersund, Sweden",
      OSR: "Ostrava, Czech Republic",
      YOW: "Ottawa, ON , Canada ",
      OUA: "Ouagadougou, Burkina Faso",
      OUL: "Oulu, Finland",
      OWB: "Owensboro, KY , USA ",
      OXR: "Oxnard, CA , USA ",
      PAD: "Paderborn, Germany",
      PAH: "Paducah, KY , USA ",
      PGA: "Page, AZ, USA ",
      PPG: "Pago Pago, Tutuila, American Samoa",
      PJA: "Pajala, Sweden",
      PLM: "Palembang, Sumatra, Indonesia",
      PMO: "Palermo, Sicily, Italy",
      PSP: "Palm Springs, CA , USA ",
      PMI: "Palma, Mallorca, Spain",
      PMW: "Palmas, Brazil",
      PMR: "Palmerston North, New Zealand",
      PNA: "Pamplona, Spain",
      PTY: "Panama City, Panama",
      PFN: "Panama City, FL , USA ",
      PPT: "Papeete, Tahiti, French Polynesia",
      PFO: "Paphos, Cyprus",
      PBO: "Paraburdoo, W.A., Australia",
      PBM: "Paramaribo, Suriname",
      CDG: "Paris, France",
      ORY: "Paris, France",
      PAR: "Paris, France",
      PKB: "Parkersburg, WV , USA ",
      PKE: "Parkes, N.S.W., Australia",
      PSC: "Pasco, WA , USA ",
      PUF: "Pau, France",
      PLN: "Pellston, MI , USA ",
      PEN: "Penang, Penang Island, Malaysia",
      PDT: "Pendleton, OR , USA ",
      PNS: "Pensacola, FL , USA ",
      YYF: "Penticton, BC , Canada ",
      PIA: "Peoria, IL , USA ",
      PGF: "Perpignan, France",
      PER: "Perth, W.A., Australia",
      PEG: "Perugia, Italy",
      PEW: "Peshawar, Pakistan",
      PKC: "Petropavlovsk-Kamchatsky, Siberia, Russia",
      PHL: "Philadelphia, PA , USA ",
      SXM: "Philipsburg, St. Maarten",
      PHS: "Phitsanulok, Thailand",
      PNH: "Phnom Penh, Cambodia",
      PHX: "Phoenix, AZ , USA ",
      HKT: "Phuket, Thailand",
      PDS: "Piedras Negras, Mexico",
      PIR: "Pierre, SD , USA ",
      SOP: "Pinehurst, NC , USA ",
      PSA: "Pisa, Italy",
      PIT: "Pittsburgh, PA , USA ",
      PLJ: "Placencia, Belize",
      PLB: "Plattsburgh, NY , USA ",
      PXU: "Pleiku, Vietnam",
      PIH: "Pocatello, ID , USA ",
      PNI: "Pohnpei, Micronesia",
      PTP: "Pointe-A-Pitre, Grande-Terre, Guadeloupe",
      PNC: "Ponca City, OK , USA ",
      PDL: "Ponta Delgada, Sao Miguel Island, Azores",
      YZT: "Port Hardy, BC, Canada ",
      PHE: "Port Hedland, W.A., Australia",
      PLO: "Port Lincoln, S.A., Australia",
      PQQ: "Port Macquarie, N.S.W., Australia",
      POM: "Port Moresby, Papua-New Guinea",
      POS: "Port of Spain, Trinidad and Tobago",
      VLI: "Port Vila, Efate Island, Vanuatu",
      PAP: "Port-au-Prince, Haiti",
      PWM: "Portland, ME , USA ",
      PDX: "Portland, OR , USA ",
      PTJ: "Portland, Vic., Australia",
      OPO: "Porto, Portugal",
      POA: "Porto Alegre, Brazil",
      PXO: "Porto Santo, Madeira",
      PSM: "Portsmouth, NH , USA ",
      YPW: "Powell River, BC , Canada ",
      POZ: "Poznan, Poland",
      PRG: "Prague, Czech Republic",
      PRC: "Prescott, AZ , USA ",
      PQI: "Presque Isle, ME , USA ",
      YXS: "Prince George, BC , Canada ",
      YPR: "Prince Rupert, BC , Canada ",
      PPP: "Proserpine, Qld., Australia",
      PVD: "Providence, RI , USA ",
      PLS: "Providenciales Island, Turks and Caicos Islands",
      PVC: "Provincetown, MA , USA ",
      ZPC: "Pucon, Chile",
      PBC: "Puebla, Mexico",
      PUB: "Pueblo, CO , USA ",
      FUE: "Puerto del Rosario, Fuerteventura Island, Canary Islands",
      PXM: "Puerto Escondido, Mexico",
      PMC: "Puerto Montt, Chile",
      POP: "Puerto Plata, Dominican Republic",
      PPS: "Puerto Princesa, Philippines",
      PVR: "Puerto Vallarta, Mexico",
      PUW: "Pullman, WA , USA ",
      PUQ: "Punta Arenas, Tierra del Fuego, Chile",
      PUJ: "Punta Cana, Dominican Republic",
      PND: "Punta Gorda, Belize",
      PUT: "Puttaparthi, India",
      FNJ: "Pyongyang, North Korea",
      TAO: "Qingdao, China",
      YQB: "Quebec, PQ , Canada ",
      ZQN: "Queenstown, New Zealand",
      QRO: "Queretaro, Mexico",
      YQZ: "Quesnel, BC , Canada ",
      UIP: "Quimper, France",
      UIN: "Quincy, IL , USA ",
      UIO: "Quito, Ecuador",
      VKG: "Rach Gia, Vietnam",
      RDU: "Raleigh, NC , USA ",
      RGN: "Rangoon, Myanmar (Burma)",
      YRT: "Rankin Inlet, NWT, Canada",
      UNN: "Ranong, Thailand",
      RAP: "Rapid City, SD , USA ",
      REC: "Recife, Brazil",
      YRL: "Red Lake, ON , Canada ",
      RDD: "Redding, CA , USA ",
      RDM: "Redmond, OR , USA ",
      REG: "Reggio di Calabria, Italy",
      YQR: "Regina, SK , Canada ",
      RNS: "Rennes, France",
      RNO: "Reno, NV , USA ",
      KEF: "Reykjavik, Iceland",
      REK: "Reykjavik, Iceland",
      RKV: "Reykjavik, Iceland",
      REX: "Reynosa, Mexico",
      RHI: "Rhinelander, WI, USA ",
      RHO: "Rhodes, Greece",
      RIC: "Richmond, VA , USA ",
      RIX: "Riga, Latvia",
      RMI: "Rimini, Italy",
      GIG: "Rio de Janeiro, Brazil",
      RIO: "Rio de Janeiro, Brazil",
      SDU: "Rio de Janeiro, Brazil",
      RIW: "Riverton, WY , USA ",
      RUH: "Riyadh, Saudi Arabia",
      ROA: "Roanoke, VA , USA ",
      YRJ: "Roberval, PQ , Canada ",
      RST: "Rochester, MN , USA ",
      ROC: "Rochester, NY , USA ",
      RSD: "Rock Sound, Bahamas",
      RKS: "Rock Springs, WY , USA ",
      RFD: "Rockford, IL , USA ",
      ROK: "Rockhampton, Qld., Australia",
      RKD: "Rockland, ME , USA ",
      RDZ: "Rodez, France",
      RMA: "Roma, Qld., Australia",
      CIA: "Rome, Italy",
      FCO: "Rome, Italy (FCO-Leonardo Da Vinci",
      ROM: "Rome, Italy",
      RNN: "Ronne, Denmark",
      RNB:"Ronneby, Sweden",
      DOM:"Roseau, Dominica",
      ROV:"Rostov, Russia",
      ROW:"Roswell, NM , USA ",
      ROT:"Rotorua, New Zealand",
      RTM:"Rotterdam, Netherlands",
      URO:"Rouen, France",
      YUY:"Rouyn-Noranda, PQ , Canada ",
      RVN:"Rovaniemi, Finland",
      RXS:"Roxas City, Philippines",
      RUT:"Rutland, VT , USA ",
      RZE:"Rzeszow, Poland",
      SAB:"Saba Island, Saba",
      SMF:"Sacramento, CA , USA ",
      HSG:"Saga, Japan",
      MBS:"Saginaw, MI , USA ",
      YSJ:"Saint John, NB , Canada ",
      RUN:"Saint-Denis, Reunion",
      ZSE:"Saint-Pierre, Reunion",
      SPN:"Saipan, Northern Mariana Islands",
      SLN:"Salina, KS , USA ",
      SBY:"Salisbury, MD , USA ",
      SLC:"Salt Lake City, UT , USA ",
      SLW:"Saltillo, Mexico",
      SSA:"Salvador, Brazil",
      SZG:"Salzburg, Austria",
      SZF:"Samsun, Turkey",
      ADZ:"San Andres, Colombia",
      SAQ:"San Andros, Bahamas",
      SJT:"San Angelo, TX , USA ",
      SAT:"San Antonio, TX , USA ",
      BRC:"San Carlos de Bariloche, Argentina",
      SAN:"San Diego, CA , USA ",
      QSF:"San Francisco, CA , USA ",
      SFO:"San Francisco, CA , USA ",
      SJO:"San Jose, Costa Rica",
      SJC:"San Jose, CA , USA ",
      SJU:"San Juan, Puerto Rico",
      SBP:"San Luis Obispo, CA , USA ",
      SLP:"San Luis Potosi, Mexico",
      SAL:"San Salvador, El Salvador",
      EAS:"San Sebastian, Spain",
      SAH:"Sanaa, Yemen",
      SDP:"Sand Point, AK , USA ",
      SDK:"Sandakan, Sabah, Malaysia",
      TRF:"Sandefjord, Norway",
      YZP:"Sandspit, Queen Charlotte Islands, BC, Canada ",
      SBA:"Santa Barbara, CA , USA ",
      SPC:"Santa Cruz, Spain",
      TFN:"Santa Cruz de Tenerife, Canary Islands",
      SAF:"Santa Fe, NM , USA ",
      SMX:"Santa Maria, CA , USA ",
      SID:"Santa Maria, Sal Island, Cape Verde",
      RSA:"Santa Rosa, Argentina",
      STS:"Santa Rosa, CA , USA ",
      SDR:"Santander, Spain",
      SCL:"Santiago, Chile",
      STI:"Santiago, Dominican Republic",
      SDQ:"Santo Domingo, Dominican Republic",
      SYX:"Sanya, China",
      SJP:"Sao Jose So Rio Preto, Brazil",
      CGH:"Sao Paulo, Brazil",
      GRU:"Sao Paulo, Brazil",
      SAO:"Sao Paulo, Brazil",
      CTS:"Sapporo, Japan",
      OKD:"Sapporo, Japan",
      SJJ:"Sarajevo, Bosnia and Herzegovina",
      SLK:"Saranac Lake, NY , USA ",
      SRQ:"Sarasota, FL , USA ",
      YZR:"Sarnia, ON , Canada ",
      YXE:"Saskatoon, SK , Canada ",
      CIU:"Sault Ste. Marie, MI, USA ",
      YAM:"Sault Ste. Marie, ON, Canada ",
      SAV:"Savannah, GA , USA ",
      BFF:"Scottsbluff, NE , USA ",
      SEA:"Seattle, WA , USA ",
      PLX:"Semipalatinsk, Kazakhstan",
      GMP:"Seoul, Korea, Republic of",
      ICN:"Seoul, Korea, Republic of",
      YZV:"Sept-Iles, PQ, Canada ",
      SVQ:"Seville, Spain",
      PVG:"Shanghai, China",
      SHA:"Shanghai, China",
      SNN:"Shannon, Ireland",
      SWA:"Shantou, China",
      SHJ:"Sharjah, United Arab Emirates",
      SSH:"Sharm El Sheikh, Egypt",
      SHD:"Shenandoah Valley Airport, VA , USA ",
      SHE:"Shenyang, China",
      SZX:"Shenzhen, China",
      SHR:"Sheridan, WY , USA ",
      SJW:"Shijiazhuang, China",
      SHV:"Shreveport, LA , USA ",
      SBW:"Sibu, Sarawak, Malaysia",
      SDY:"Sidney, MT , USA ",
      SVC:"Silver City, NM , USA ",
      SIN:"Singapore, Singapore",
      SUX:"Sioux City, IA , USA ",
      FSD:"Sioux Falls, SD , USA ",
      YXL:"Sioux Lookout, ON, Canada ",
      SIT:"Sitka, AK , USA ",
      SGY:"Skagway, AK , USA ",
      SFT:"Skelleftea, Sweden",
      SKP:"Skopje, Macedonia",
      YYD:"Smithers, BC, Canada ",
      SOF:"Sofia, Bulgaria",
      SGD:"Sonderborg, Denmark",
      JZH:"Songpan Jiuzhai Huanglong, China",
      TZN:"South Andros, Bahamas",
      SBN:"South Bend, IN , USA ",
      SOU:"Southampton, England",
      SPU:"Split, Croatia",
      GEG:"Spokane, WA , USA ",
      SPI:"Springfield, IL , USA ",
      CEF:"Springfield, MA , USA ",
      SGF:"Springfield, MO , USA ",
      VSF:"Springfield, VT , USA ",
      STC:"St. Cloud, MN , USA ",
      SGU:"St. George, UT , USA ",
      GND:"St. George's, Grenada",
      ANU:"St. John's, Antigua",
      YYT:"St. John's, NF , Canada ",
      STL:"St. Louis, MO , USA ",
      LED:"St. Petersburg, Russia",
      PIE:"St. Petersburg, FL , USA ",
      SCE:"State College, PA , USA ",
      SVG:"Stavanger, Norway",
      SBS:"Steamboat Springs, CO , USA ",
      SML:"Stella Maris, Long Island, Bahamas",
      ARN:"Stockholm, Sweden",
      BMA:"Stockholm, Sweden",
      STO:"Stockholm, Sweden",
      SYY:"Stornoway, Isle of Lewis, Scotland",
      SQO:"Storuman, Sweden",
      SXB:"Strasbourg, France",
      STR:"Stuttgart, Germany",
      SFS:"Subic Bay, Philippines",
      YSB:"Sudbury, ON , Canada ",
      THS:"Sukhothai, Thailand",
      SUN:"Sun Valley, ID , USA ",
      SDL:"Sundsvall, Sweden",
      SUB:"Surabaya, Java, Indonesia",
      URT:"Surat Thani, Thailand",
      SUV:"Suva, Fiji",
      YQY:"Sydney, Cape Breton Island, NS, Canada ",
      SYD:"Sydney, N.S.W., Australia",
      SYR:"Syracuse, NY , USA ",
      SZZ:"Szczecin, Poland",
      TCP:"Taba, Egypt",
      TBZ:"Tabriz, Iran",
      TAC:"Tacloban, Philippines",
      TAE:"Taegu, South Korea",
      TAG:"Tagbilaran, Philippines",
      RMQ:"Taichung, Taiwan",
      TPE:"Taipei, Taiwan",
      TSA:"Taipei, Taiwan",
      TYN:"Taiyuan, China",
      TAK:"Takamatsu, Japan",
      TLH:"Tallahassee, FL , USA ",
      TLL:"Tallinn, Estonia",
      TPA:"Tampa, FL , USA ",
      TMP:"Tampere, Finland",
      TAM:"Tampico, Mexico",
      TMW:"Tamworth, N.S.W., Australia",
      TNG:"Tangier, Morocco",
      TAP:"Tapachula, Mexico",
      TAS:"Tashkent, Uzbekistan",
      TUO:"Taupo, New Zealand",
      TRG:"Tauranga, New Zealand",
      TWU:"Tawau, Sabah, Malaysia",
      TBS:"Tbilisi, Georgia",
      MME:"Teesside, England",
      TGU:"Tegucigalpa, Honduras",
      THR:"Tehran, Iran",
      TLV:"Tel Aviv, Israel",
      TEX:"Telluride, CO, USA ",
      ZCO:"Temuco, Chile",
      TCI:"Tenerife Island, Canary Islands",
      TFS:"Tenerife Island, Canary Islands",
      TV:"Tenerife Island, Canary Islands",
      TPQ:"Tepic, Mexico",
      TMJ:"Termez, Uzbekistan",
      YXT:"Terrace, BC, Canada ",
      TXK:"Texarkana, AR , USA ",
      AXA:"The Valley, Anguilla",
      SKG:"Thessaloniki, Greece",
      TVF:"Thief River Falls, MN , USA ",
      JTR:"Thira, Santorini Island, Greece",
      YTH:"Thompson, MB , Canada ",
      YQT:"Thunder Bay, ON , Canada ",
      TSN:"Tianjin, China",
      TIJ:"Tijuana, Mexico",
      TIU:"Timaru, New Zealand",
      YTS:"Timmins, ON , Canada ",
      TIA:"Tirana, Albania",
      TAB:"Tobago, Trinidad and Tobago",
      OOK:"Toksook Bay, AK , USA ",
      HND:"Tokyo, Japan",
      NRT:"Tokyo, Japan",
      TYO:"Tokyo, Japan",
      TOL:"Toledo, OH , USA ",
      TLC:"Toluca, Mexico",
      TEN:"Tongren, China",
      TOP:"Topeka, KS , USA ",
      YTO:"Toronto, ON , Canada ",
      YTZ:"Toronto, ON , Canada ",
      YYZ:"Toronto, ON , Canada ",
      TRC:"Torreon, Mexico",
      TLN:"Toulon, France",
      TLS:"Toulouse, France",
      TSV:"Townsville, Qld., Australia",
      TST:"Trang, Thailand",
      TDX:"Trat, Thailand",
      TVC:"Traverse City, MI , USA ",
      TCB:"Treasure Cay, Abaco Island, Bahamas",
      TTN:"Trenton, NJ , USA ",
      TRI:"Tri-City Airport, TN , USA ",
      TRS:"Trieste, Italy",
      TIP:"Tripoli, Libya",
      TOS:"Tromso, Norway",
      TRD:"Trondheim, Norway",
      TKK:"Truk, Micronesia",
      TUS:"Tucson, AZ , USA ",
      TUL:"Tulsa, OK , USA ",
      TUN:"Tunis, Tunisia",
      TUP:"Tupelo, MS , USA ",
      TRN:"Turin, Italy",
      TKU:"Turku, Finland",
      TGZ:"Tuxtla Gutierrez, Mexico",
      TWF:"Twin Falls, ID , USA ",
      TYR:"Tyler, TX , USA ",
      UBP:"Ubon Ratchathani, Thailand",
      UTH:"Udon Thani, Thailand",
      UPG:"Ujung Pandang, Sulawesi, Indonesia",
      ULN:"Ulan Bator, Mongolia",
      UME:"Umea, Sweden",
      UNA:"Una, Brazil",
      UNK:"Unalakleet, AK , USA ",
      URC:"Urumqi, Sinkiang, China",
      USH:"Ushuaia, Tierra del Fuego, Argentina",
      UKK:"Ust Kamenogorsk, Kazakhstan",
      UTP:"Utapao, Thailand",
      VAA:"Vaasa, Finland",
      EGE:"Vail, CO , USA ",
      YVO:"Val-d'Or, PQ, Canada ",
      VDZ:"Valdez, AK , USA ",
      ZAL:"Valdivia, Chile",
      VLD:"Valdosta, GA , USA ",
      VLC:"Valencia, Spain",
      VLL:"Valladolid, Spain",
      MLA:"Valletta, Malta",
      YVR:"Vancouver, BC , Canada ",
      VNS:"Varanasi, India",
      VAR:"Varna, Bulgaria",
      VST:"Vasteras, Sweden",
      VXO:"Vaxjo, Sweden",
      VCE:"Venice, Italy",
      VER:"Veracruz, Mexico",
      VRN:"Verona, Italy",
      YYJ:"Victoria, BC , Canada ",
      SEZ:"Victoria, Mahe Island, Seychelles",
      VCT:"Victoria, TX , USA ",
      VIE:"Vienna, Austria",
      VTE:"Vientiane, Laos",
      VQS:"Vieques, Puerto Rico",
      UVF:"Vieux Fort, St. Lucia",
      VGO:"Vigo, Spain",
      VHM:"Vilhelmina, Sweden",
      VSA:"Villahermosa, Mexico",
      VNO:"Vilnius, Lithuania",
      VII:"Vinh City, Vietnam",
      VIS:"Visalia, CA , USA ",
      VBY:"Visby, Sweden",
      VIT:"Vitoria, Spain",
      VVO:"Vladivostok, Siberia, Russia",
      VOG:"Volgograd, Russia",
      YWK:"Wabush, Labrador, NF , Canada ",
      ACT:"Waco, TX , USA ",
      WGA:"Wagga-Wagga, N.S.W., Australia",
      NTQ:"Wajima, Japan",
      ALW:"Walla Walla, WA , USA ",
      WAG:"Wanganui, New Zealand",
      QRW:"Warri, Nigeria",
      WAW:"Warsaw, Poland",
      DCA:"Washington DC , USA ",
      IAD:"Washington DC , USA ",
      WAS:"Washington DC , USA ",
      ALO:"Waterloo, IA , USA ",
      ART:"Watertown, NY , USA ",
      ATY:"Watertown, SD , USA ",
      CWA:"Wausau, WI , USA ",
      WEI:"Weipa, Qld., Australia",
      WLG:"Wellington, New Zealand",
      EAT:"Wenatchee, WA , USA ",
      PBI:"West Palm Beach, FL , USA ",
      WYS:"West Yellowstone, MT, USA ",
      WSZ:"Westport, New Zealand",
      WHK:"Whakatane, New Zealand",
      WRE:"Whangarei, New Zealand",
      HPN:"White Plains, NY , USA ",
      YXY:"Whitehorse, YT , Canada ",
      WYA:"Whyalla, S.A., Australia",
      SPS:"Wichita Falls, TX , USA ",
      ICT:"Wichita, KS , USA ",
      WIC:"Wick, Scotland",
      AVP:"Wilkes-Barre, PA , USA ",
      CUR:"Willemstad, Curacao",
      YWL:"Williams Lake, BC, Canada ",
      IPT:"Williamsport, PA , USA ",
      ISN:"Williston, ND , USA ",
      ILG:"Wilmington, DE , USA ",
      ILM:"Wilmington, NC , USA ",
      YQG:"Windsor, ON , Canada ",
      YWG:"Winnipeg, MB, Canada",
      OLF:"Wolf Point, MT, USA ",
      WRL:"Worland, WY , USA ",
      WRG:"Wrangell, AK , USA ",
      WRO:"Wroclaw, Poland",
      WUH:"Wuhan, China",
      XIY:"Xi'an, China",
      XMN:"Xiamen, China",
      XIC:"Xichang, China",
      YKM:"Yakima, WA , USA ",
      YAK:"Yakutat, AK , USA ",
      GAJ:"Yamagata, Japan",
      YNY:"Yangyang, Korea, Republic of",
      YNJ:"Yanji, China",
      YNT:"Yantai, China",
      NSI:"Yaounde, Cameroon",
      YAO:"Yaounde, Cameroon",
      YAP:"Yap, Micronesia",
      YZF:"Yellowknife, NWT, Canada",
      EVN:"Yerevan, Armenia",
      JOG:"Yogyakarta, Java, Indonesia",
      YUM:"Yuma, AZ , USA ",
      ZCL:"Zacatecas, Mexico",
      ZAD:"Zadar, Croatia",
      ZAG:"Zagreb, Croatia",
      ZAM:"Zamboanga, Philippines",
      ZNZ:"Zanzibar, Tanzania",
      ZAZ:"Zaragoza, Spain",
      CGO:"Zhengzhou, China",
      HSN:"Zhoushan, China",
      ZRH:"Zurich, Switzerland",
      KMI:"Miyazaki, Japan",
      MOB:"Mobile, AL , USA ",
      MOD:"Modesto, CA , USA ",
      MGQ:"Mogadishu, Somalia",
      MLI:"Moline, IL , USA ",
      MBA:"Mombasa, Kenya",
      MIR:"Monastir, Tunisia",
      LOV:"Monclova, Mexico",
      YQM:"Moncton, NB , Canada ",
      MLU:"Monroe, LA , USA ",
      ROB:"Monrovia, Liberia",
      YYY:"Mont-Joli, PQ , Canada ",
      MBJ:"Montego Bay, Jamaica",
      MRY:"Monterey, CA , USA ",
      MTY:"Monterrey, Mexico",
      MVD:"Montevideo, Uruguay",
      MGM:"Montgomery, AL , USA ",
      MPL:"Montpellier, France",
      YMQ:"Montreal, PQ , Canada ",
      YUL:"Montreal, PQ , Canada ",
      MTJ:"Montrose, CO , USA ",
      MXX:"Mora, Sweden",
      MRZ:"Moree, N.S.W., Australia",
      MLM:"Morelia, Mexico",
      MGW:"Morgantown, WV , USA ",
      HAH:"Moroni, Comoro Islands",
      MYA:"Moruya, N.S.W., Australia",
      MOW:"Moscow, Russia",
      SVO:"Moscow, Russia",
      VKO:"Moscow, Russia",
      MWH:"Moses Lake, WA, USA ",
      MGB:"Mount Gambier, S.A., Australia",
      ISA:"Mount Isa, Qld., Australia",
      MDG:"Mudanjiang, China",
      EAP:"Mulhouse, France",
      MLH:"Mulhouse, France",
      MZV:"Mulu, Malaysia",
      BOM:"Mumbai (Bombay), India",
      MUC:"Munich, Germany",
      FMO:"Munster, Germany",
      MJV:"Murcia, Spain",
      MMK:"Murmansk, Russia",
      MCT:"Muscat, Oman",
      MSL:"Muscle Shoals, AL, USA ",
      MKG:"Muskegon, MI , USA ",
      MYR:"Myrtle Beach, SC , USA ",
      MJT:"Mytilene, Lesbos Island, Greece",
      NDJ:"N'Djamena, Chad",
      NAN:"Nadi, Fiji",
      NDR:"Nador, Morocco",
      NGS:"Nagasaki, Japan",
      NGO:"Nagoya, Japan",
      NKM:"Nagoya, Japan",
      OKA:"Naha, Okinawa, Japan",
      NBO:"Nairobi, Kenya",
      NST:"Nakhon Si Thammarat, Thailand",
      YCD:"Nanaimo, BC , Canada ",
      KHN:"Nanchang, China",
      LZN:"Nangen, Taiwan",
      NKG:"Nanjing, China",
      SHM:"Nanki Shirahama, Japan",
      NNG:"Nanning, China",
      NTE:"Nantes, France",
      ACK:"Nantucket, MA , USA ",
      NPE:"Napier, New Zealand",
      NAP:"Naples, Italy",
      APF:"Naples, FL , USA ",
      NAA:"Narrabri, N.S.W., Australia",
      NRA:"Narrandera, N.S.W., Australia",
      NVK:"Narvik, Norway",
      NNM:"Naryan Mar, Russia",
      BNA:"Nashville, TN , USA ",
      NAS:"Nassau, Bahamas",
      PID:"Nassau, Bahamas",
      ASJ:"Naze, Amami-O Island, Japan",
      NSN:"Nelson, New Zealand",
      MQP:"Nelspruit, South Africa",
      EWN:"New Bern, NC , USA ",
      HVN:"New Haven, CT , USA ",
      MSY:"New Orleans, LA , USA ",
      JFK:"New York, NY , USA ",
      LGA:"New York, NY , USA ",
      NYC:"New York, NY , USA ",
      EWR:"Newark, NJ , USA ",
      SWF:"Newburgh, NY , USA ",
      NCL:"Newcastle, England",
      NTL:"Newcastle, N.S.W., Australia",
      ZNE:"Newman, W.A., Australia",
      PHF:"Newport News, VA , USA ",
      NIM:"Niamey, Niger",
      NCE:"Nice, France",
      KIJ:"Niigata, Japan",
      NGB:"Ningbo, China",
      GOJ:"Nizhniy Novgorod, Russia",
      OME:"Nome, AK , USA ",
      ORL:"Orlando, Florida, USA",
      AKJ: "Hokkaido, Japan",
      SEL: "Seoul, Korea",
      OKJ:"Okayama, Japan",
      FMY: "Southwest Florida, USA",
      YEA: "Edmonton, Alberta, Canada"
    }

    // exports.name = airportNamesLookup;